# action.yml
name: "Flutter Test and Coverage"
description: "Run Flutter tests and generate coverage report"
inputs:
  flutter-version:
    description: "Version of Flutter to use"
    required: true
  java-version:
    description: "Version of Java to use"
    required: true
runs:
  using: "composite"
  defaults:
    run:
      shell: "bash"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "adopt"

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: |
          /opt/hostedtoolcache/flutter
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Install dependencies
      run: flutter packages get

    - name: Run Tests
      id: tests
      run: |
        TESTS_RESULTS=$(flutter test --coverage)
        echo "$TESTS_RESULTS" >> $GITHUB_STEP_SUMMARY

    - name: Install LCOV
      run: |
        sudo apt-get install lcov

    - name: Generate LCOV summary
      id: lcov
      run: |
        LCOV_SUMMARY=$(lcov --summary coverage/lcov.info)
        echo "$LCOV_SUMMARY" >> $GITHUB_STEP_SUMMARY

    - name: Convert LCOV to HTML
      run: |
        genhtml coverage/lcov.info -o coverage/html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/html/
