# action.yml
name: "Flutter Analyze"
description: "Run Flutter analyze on your Dart code"
inputs:
  flutter-version:
    description: "Version of Flutter to use"
    required: true
runs:
  using: "composite"
  defaults:
    run:
      shell: "bash"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Install dependencies
      run: flutter packages get

    - name: Run Flutter Analyze
      run: echo $(flutter analyze) >> $GITHUB_STEP_SUMMARY
